#version 460
#extension GL_GOOGLE_include_directive    : enable
#include "head.glsl"
#include "state.glsl"
layout(set = 1, binding = 0) uniform sampler2D img_in;
layout(set = 1, binding = 1, std430) readonly buffer buf_prep_t { filmsim_state_t prep; };
layout(set = 1, binding = 2) uniform sampler2D img_curvewarp;
layout(set = 1, binding = 3) uniform sampler2D img_coupler;
layout(set = 1, binding = 4) uniform writeonly restrict image2D img_out;
#include "state_ops.glsl"
#include "sampling.glsl"

void main()
{
  FILMSIM_BOUNDS_INIT(ipos);
  vec3 log_raw = fetch_coupler_subtracted_exposure(ipos, img_coupler);
  vec3 raw = exp2(log_raw * log2_10);
  imageStore(img_out, ipos, vec4(raw, 1));
}
