#pragma once
// the rest of this header is autogenerated by the following script:
#if 0
#!/bin/bash

# Neutral-fit directly scanned positive stocks.

# must match film_stocks in mklut-profiles.py and the film combo in params.ui
films=(
kodak_gold_200
kodak_ultramax_400
kodak_ektar_100
kodak_portra_160
kodak_portra_400
kodak_portra_800
kodak_portra_800_push1
kodak_portra_800_push2
fujifilm_c200
fujifilm_xtra_400
fujifilm_pro_400h
kodak_vision3_50d
kodak_vision3_250d
kodak_vision3_200t
kodak_vision3_500t
kodak_verita_200d
kodak_kodachrome_64
kodak_ektachrome_100
fujifilm_provia_100f
fujifilm_velvia_100
kodak_doublex
kodak_trix
)
# index of every stock that is actually scanned directly as a positive image
positive_idx=(16 17 18 19 21)

n_films=${#films[@]}

cat << EOF > neutral-pos.cfg
frames:1
fps:0
module:const:main:23.3783:290.7
module:filmsim:01:255.558:326.7
module:display:main:719.252:340.033
module:pick:01:510.405:124.7
module:i-lut:filmsim:21.3333:441
module:i-lut:spectem:20:580.333
connect:const:main:output:filmsim:01:input
connect:i-lut:filmsim:output:filmsim:01:filmsim
connect:i-lut:spectem:output:filmsim:01:spectra
connect:filmsim:01:output:display:main:input
connect:filmsim:01:output:pick:01:input
param:const:main:nspots:1
param:const:main:mode:0
param:const:main:wd:4
param:const:main:ht:4
param:pick:01:nspots:1
param:pick:01:spots:0:1:0:1
param:pick:01:show:2
param:pick:01:grab:1
param:pick:01:freeze:0
param:i-lut:filmsim:filename:data/filmsim.lut
param:i-lut:spectem:filename:data/spectra-em.lut
param:const:main:colour:0.184:0.184:0.184:1
param:pick:01:ref:0.184:0.184:0.184
param:filmsim:01:process:1
# fit against the module defaults, couplers included, no paper involved
param:filmsim:01:couplers:1
param:filmsim:01:cp amt:1.0
param:filmsim:01:lang r:1.0
param:filmsim:01:lang g:1.0
param:filmsim:01:lang b:1.0
param:filmsim:01:cp rad:20.0
param:filmsim:01:halation:0
param:filmsim:01:grain:0
param:filmsim:01:scan ill:5000
param:filmsim:01:ev film:0
param:filmsim:01:filter c:0.5
param:filmsim:01:filter m:0.5
param:filmsim:01:filter y:0.5
EOF

# Sweep Nelder-Mead starts and keep the best fit.
starts=("0.1 0.70 0.75 0.45" "0.3 0.60 0.65 0.50" "0.2 0.85 0.90 0.35" "0.5 0.50 0.50 0.50"
        "0.05 0.90 0.95 0.30" "0.4 0.40 0.45 0.60" "0.0 0.30 0.30 1.0" "0.6 0.2 0.2 0.5"
        "0.7 0.7 0.7 -0.3" "0.9 0.9 0.9 -0.5")
GOOD=0.02

echo "// ev film, filter c, filter m, filter y" > results.txt
echo "const float pos_wb[$n_films][4] = {" >> results.txt
: > losses.txt
for f in $(seq 0 $((n_films-1)))
do
  film=${films[$f]}
  is_positive=0
  for p in ${positive_idx[@]}; do [ "$p" = "$f" ] && is_positive=1; done
  if [ "$is_positive" = "0" ]; then
    echo "{ 0, 0, 0, 0 }, //" $film $f "(not scanned as a positive)" >> results.txt
    continue
  fi
  best_loss=""; best_cfg=""
  for s in "${starts[@]}"
  do
    set -- $s
    sed -e "s/^param:filmsim:01:filter c:.*/param:filmsim:01:filter c:$1/" \
        -e "s/^param:filmsim:01:filter m:.*/param:filmsim:01:filter m:$2/" \
        -e "s/^param:filmsim:01:filter y:.*/param:filmsim:01:filter y:$3/" \
        -e "s/^param:filmsim:01:ev film:.*/param:filmsim:01:ev film:$4/" \
        neutral-pos.cfg > neutral-pos-start.cfg
    out=$(vkdt-fit -d none -g neutral-pos-start.cfg \
      --param "filmsim:01:filter c" \
      --param "filmsim:01:filter m" \
      --param "filmsim:01:filter y" \
      --param "filmsim:01:ev film" \
      --target "pick:01:de76" \
      --nelder-mead \
      --config "param:filmsim:01:film:$f" 2>&1)
    loss=$(echo "$out" | grep -oP 'post-opt loss:\s*\K[0-9.eE+-]+')
    [ -z "$loss" ] && continue
    if [ -z "$best_loss" ] || awk "BEGIN{exit !($loss < $best_loss)}"; then
      best_loss=$loss; best_cfg=$(echo "$out" | grep -E '^param:filmsim:01:')
    fi
    awk "BEGIN{exit !($best_loss <= $GOOD)}" && break
  done
  echo "$film $f loss=$best_loss" >> losses.txt
  echo "{ //" $film $f >> results.txt
  echo $(echo "$best_cfg" | grep -E '^param:filmsim:01:ev film' | cut -d: -f5), >> results.txt
  echo $(echo "$best_cfg" | grep -E '^param:filmsim:01:filter c' | cut -d: -f5), >> results.txt
  echo $(echo "$best_cfg" | grep -E '^param:filmsim:01:filter m' | cut -d: -f5), >> results.txt
  echo $(echo "$best_cfg" | grep -E '^param:filmsim:01:filter y' | cut -d: -f5), >> results.txt
  echo "}," >> results.txt
done
echo "};" >> results.txt
rm neutral-pos-start.cfg neutral-pos.cfg
#endif


// ev film, filter c, filter m, filter y
static const float pos_wb[22][4] = {
{ 0, 0, 0, 0 }, // kodak_gold_200 0 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_ultramax_400 1 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_ektar_100 2 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_portra_160 3 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_portra_400 4 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_portra_800 5 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_portra_800_push1 6 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_portra_800_push2 7 (not scanned as a positive)
{ 0, 0, 0, 0 }, // fujifilm_c200 8 (not scanned as a positive)
{ 0, 0, 0, 0 }, // fujifilm_xtra_400 9 (not scanned as a positive)
{ 0, 0, 0, 0 }, // fujifilm_pro_400h 10 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_vision3_50d 11 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_vision3_250d 12 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_vision3_200t 13 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_vision3_500t 14 (not scanned as a positive)
{ 0, 0, 0, 0 }, // kodak_verita_200d 15 (not scanned as a positive)
{ // kodak_kodachrome_64 16
-0.536916,
0.561047,
0.431235,
0.495082,
},
{ // kodak_ektachrome_100 17
-0.320157,
0.860494,
0.766657,
0.787321,
},
{ // fujifilm_provia_100f 18
-0.27308,
0.808432,
0.710001,
0.731154,
},
{ // fujifilm_velvia_100 19
-0.322643,
0.643306,
0.521866,
0.568624,
},
{ 0, 0, 0, 0 }, // kodak_doublex 20 (not scanned as a positive)
{ // kodak_trix 21
-0.377199,
0.786071,
0.700886,
0.720724,
},
};
