#pragma once
// the rest of this header is autogenerated by the following script:
#if 0
#!/bin/bash

films=(
kodak_portra_400,
kodak_ultramax_400,
kodak_gold_200,
kodak_vision3_50d,
fujifilm_pro_400h,
fujifilm_xtra_400,
fujifilm_c200
)

papers=(
kodak_endura_premier,
kodak_ektacolor_edge,
kodak_supra_endura,
kodak_portra_endura,
fujifilm_crystal_archive_typeii
)

n_films=${#films[@]}
n_papers=${#papers[@]}
# ${films[0]}

cat << EOF > neutral.cfg
frames:1
fps:0
module:const:main:23.3783:290.7
module:filmsim:01:255.558:326.7
module:display:main:719.252:340.033
module:pick:01:510.405:124.7
module:i-lut:filmsim:21.3333:441
module:i-lut:spectem:20:580.333
connect:const:main:output:filmsim:01:input
connect:i-lut:filmsim:output:filmsim:01:filmsim
connect:i-lut:spectem:output:filmsim:01:spectra
connect:filmsim:01:output:display:main:input
connect:filmsim:01:output:pick:01:input
param:const:main:nspots:1
param:const:main:colour:0.184:0.184:0.184:1
param:const:main:mode:0
param:pick:01:nspots:1
param:pick:01:spots:0:1:0:1
param:pick:01:ref:0.4821:0.5:0.41255
param:pick:01:show:2
param:pick:01:grab:1
param:pick:01:freeze:0
param:i-lut:filmsim:filename:data/filmsim.lut
param:i-lut:spectem:filename:data/spectra-em.lut
EOF

echo "// ev paper, filter c, filter m, filter y" > results.txt
echo "const float wb[$n_films][$n_papers][4] = {" >> results.txt
f=0
for film in ${films[@]}
do
  p=0
  echo "{" >> results.txt
  for paper in ${papers[@]}
  do
    echo $film $paper $f $p

    vkdt fit -d none -g neutral.cfg \
      --param "filmsim:01:filter c" \
      --param "filmsim:01:filter m" \
      --param "filmsim:01:filter y" \
      --param "filmsim:01:ev paper" \
      --target "pick:01:de76" --nelder-mead \
      --config "param:filmsim:01:film:$f" "param:filmsim:01:paper:$p" > neutral-opt.cfg
    echo "{ //" $film $paper $f $p >> results.txt
    echo $(cat neutral-opt.cfg | grep -E '^param:filmsim:01:ev paper' | cut -d: -f5), >> results.txt
    echo $(cat neutral-opt.cfg | grep -E '^param:filmsim:01:filter c' | cut -d: -f5), >> results.txt
    echo $(cat neutral-opt.cfg | grep -E '^param:filmsim:01:filter m' | cut -d: -f5), >> results.txt
    echo $(cat neutral-opt.cfg | grep -E '^param:filmsim:01:filter y' | cut -d: -f5), >> results.txt
    echo "}," >> results.txt
    p=$((p+1))
  done
  echo "}," >> results.txt
  f=$((f+1))
done
echo "};" >> results.txt
rm neutral-opt.cfg
#endif

// ev paper, filter c, filter m, filter y
const float wb[7][5][4] = {
{
{ // kodak_portra_400, kodak_endura_premier, 0 0
-0.0141673,
0.425543,
0.463228,
0.660222,
},
{ // kodak_portra_400, kodak_ektacolor_edge, 0 1
0.0556513,
0.312093,
0.364765,
0.824718,
},
{ // kodak_portra_400, kodak_supra_endura, 0 2
0.679507,
0.65176,
-1.29272,
0.943966,
},
{ // kodak_portra_400, kodak_portra_endura, 0 3
0.896902,
0.688175,
-1.16146,
0.954374,
},
{ // kodak_portra_400, fujifilm_crystal_archive_typeii 0 4
-0.395776,
0.564109,
0.505288,
0.880555,
},
},
{
{ // kodak_ultramax_400, kodak_endura_premier, 1 0
-0.041455,
0.441368,
0.519886,
0.722011,
},
{ // kodak_ultramax_400, kodak_ektacolor_edge, 1 1
-0.01364,
0.322592,
0.425716,
0.841982,
},
{ // kodak_ultramax_400, kodak_supra_endura, 1 2
2.12961,
0.828379,
0.0733023,
0.979595,
},
{ // kodak_ultramax_400, kodak_portra_endura, 1 3
0.887933,
0.681495,
-0.861163,
0.959593,
},
{ // kodak_ultramax_400, fujifilm_crystal_archive_typeii 1 4
-0.487177,
0.574443,
0.543808,
0.890889,
},
},
{
{ // kodak_gold_200, kodak_endura_premier, 2 0
-0.334266,
0.624549,
0.61198,
0.735567,
},
{ // kodak_gold_200, kodak_ektacolor_edge, 2 1
-0.333814,
0.53665,
0.530143,
0.834898,
},
{ // kodak_gold_200, kodak_supra_endura, 2 2
-0.199582,
0.588339,
-0.758492,
0.910462,
},
{ // kodak_gold_200, kodak_portra_endura, 2 3
0.342324,
0.69792,
-0.496735,
0.940582,
},
{ // kodak_gold_200, fujifilm_crystal_archive_typeii 2 4
-0.733624,
0.735761,
0.64156,
0.897271,
},
},
{
{ // kodak_vision3_50d, kodak_endura_premier, 3 0
-0.739046,
0.820527,
0.847651,
0.892861,
},
{ // kodak_vision3_50d, kodak_ektacolor_edge, 3 1
-0.863462,
0.760068,
0.780353,
0.913997,
},
{ // kodak_vision3_50d, kodak_supra_endura, 3 2
-0.456103,
0.672262,
0.798153,
0.574387,
},
{ // kodak_vision3_50d, kodak_portra_endura, 3 3
-0.431915,
0.814495,
0.0904288,
0.955192,
},
{ // kodak_vision3_50d, fujifilm_crystal_archive_typeii 3 4
-1.11532,
0.872617,
0.850161,
0.949318,
},
},
{
{ // fujifilm_pro_400h, kodak_endura_premier, 4 0
-1.08871,
0.768692,
0.769518,
0.841719,
},
{ // fujifilm_pro_400h, kodak_ektacolor_edge, 4 1
-0.680786,
0.762427,
0.791596,
0.911146,
},
{ // fujifilm_pro_400h, kodak_supra_endura, 4 2
0.0872235,
0.847505,
0.357228,
0.950491,
},
{ // fujifilm_pro_400h, kodak_portra_endura, 4 3
-0.254781,
0.810044,
0.208453,
0.942679,
},
{ // fujifilm_pro_400h, fujifilm_crystal_archive_typeii 4 4
-1.1638,
0.856914,
0.833082,
0.94053,
},
},
{
{ // fujifilm_xtra_400, kodak_endura_premier, 5 0
-0.460409,
0.78813,
0.830167,
0.915108,
},
{ // fujifilm_xtra_400, kodak_ektacolor_edge, 5 1
-0.775497,
0.65161,
0.758784,
0.922149,
},
{ // fujifilm_xtra_400, kodak_supra_endura, 5 2
-0.431831,
0.712608,
0.103778,
0.950085,
},
{ // fujifilm_xtra_400, kodak_portra_endura, 5 3
-0.308859,
0.732199,
0.115179,
0.957111,
},
{ // fujifilm_xtra_400, fujifilm_crystal_archive_typeii 5 4
-1.08094,
0.80864,
0.82657,
0.953221,
},
},
{
{ // fujifilm_c200 kodak_endura_premier, 6 0
-1.81003,
0.475371,
0.63659,
0.815774,
},
{ // fujifilm_c200 kodak_ektacolor_edge, 6 1
-0.782257,
0.644911,
0.7784,
0.928638,
},
{ // fujifilm_c200 kodak_supra_endura, 6 2
-0.442847,
0.696483,
0.210502,
0.945289,
},
{ // fujifilm_c200 kodak_portra_endura, 6 3
-0.334515,
0.715042,
0.211264,
0.952589,
},
{ // fujifilm_c200 fujifilm_crystal_archive_typeii 6 4
-0.903413,
0.835005,
0.859373,
0.962242,
},
},
};
