#version 460
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform sampler2D img_in;
layout(set = 0, binding = 1) uniform writeonly image2D img_out;
void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(img_out);
    if(pos.x >= size.x || pos.y >= size.y) return;
    vec2 uv = (vec2(pos) + 0.5) / vec2(size);
    vec4 color = texture(img_in, uv);
    imageStore(img_out, pos, color);
}
