PIPE_O=\
pipe/alloc.o\
pipe/connector.o\
pipe/global.o\
pipe/graph.o\
pipe/graph-io.o\
pipe/graph-export.o\
pipe/module.o
PIPE_H=\
pipe/alloc.h\
pipe/connector.h\
pipe/connector.inc\
pipe/dlist.h\
pipe/global.h\
pipe/graph.h\
pipe/graph-io.h\
pipe/graph-print.h\
pipe/graph-export.h\
pipe/graph-traverse.inc\
pipe/modules/api.h\
pipe/io.h\
pipe/module.h\
pipe/node.h\
pipe/params.h\
pipe/pipe.h\
pipe/token.h
PIPE_CFLAGS=
PIPE_LDFLAGS=-ldl
