#pragma once
// clutch header between pipewire and libav

// copied from pipewire so we don't depend on it:
enum spa_audio_format_copy {
	SPA_AUDIO_FORMAT_UNKNOWN,
	SPA_AUDIO_FORMAT_ENCODED,

	/* interleaved formats */
	SPA_AUDIO_FORMAT_START_Interleaved	= 0x100,
	SPA_AUDIO_FORMAT_S8,
	SPA_AUDIO_FORMAT_U8,
	SPA_AUDIO_FORMAT_S16_LE,
	SPA_AUDIO_FORMAT_S16_BE,
	SPA_AUDIO_FORMAT_U16_LE,
	SPA_AUDIO_FORMAT_U16_BE,
	SPA_AUDIO_FORMAT_S24_32_LE,
	SPA_AUDIO_FORMAT_S24_32_BE,
	SPA_AUDIO_FORMAT_U24_32_LE,
	SPA_AUDIO_FORMAT_U24_32_BE,
	SPA_AUDIO_FORMAT_S32_LE,
	SPA_AUDIO_FORMAT_S32_BE,
	SPA_AUDIO_FORMAT_U32_LE,
	SPA_AUDIO_FORMAT_U32_BE,
	SPA_AUDIO_FORMAT_S24_LE,
	SPA_AUDIO_FORMAT_S24_BE,
	SPA_AUDIO_FORMAT_U24_LE,
	SPA_AUDIO_FORMAT_U24_BE,
	SPA_AUDIO_FORMAT_S20_LE,
	SPA_AUDIO_FORMAT_S20_BE,
	SPA_AUDIO_FORMAT_U20_LE,
	SPA_AUDIO_FORMAT_U20_BE,
	SPA_AUDIO_FORMAT_S18_LE,
	SPA_AUDIO_FORMAT_S18_BE,
	SPA_AUDIO_FORMAT_U18_LE,
	SPA_AUDIO_FORMAT_U18_BE,
	SPA_AUDIO_FORMAT_F32_LE,
	SPA_AUDIO_FORMAT_F32_BE,
	SPA_AUDIO_FORMAT_F64_LE,
	SPA_AUDIO_FORMAT_F64_BE,

	SPA_AUDIO_FORMAT_ULAW,
	SPA_AUDIO_FORMAT_ALAW,

	/* planar formats */
	SPA_AUDIO_FORMAT_START_Planar		= 0x200,
	SPA_AUDIO_FORMAT_U8P,
	SPA_AUDIO_FORMAT_S16P,
	SPA_AUDIO_FORMAT_S24_32P,
	SPA_AUDIO_FORMAT_S32P,
	SPA_AUDIO_FORMAT_S24P,
	SPA_AUDIO_FORMAT_F32P,
	SPA_AUDIO_FORMAT_F64P,
	SPA_AUDIO_FORMAT_S8P,
};

static inline int
fmt_pw_from_av(int format)
{
  switch(format) {
    case AV_SAMPLE_FMT_U8:   return SPA_AUDIO_FORMAT_U8;
    case AV_SAMPLE_FMT_S16:  return SPA_AUDIO_FORMAT_S16_LE;
    case AV_SAMPLE_FMT_S32:  return SPA_AUDIO_FORMAT_S32_LE;
    case AV_SAMPLE_FMT_FLT:  return SPA_AUDIO_FORMAT_F32_LE;
    case AV_SAMPLE_FMT_DBL:  return SPA_AUDIO_FORMAT_F64_LE;
    case AV_SAMPLE_FMT_U8P:  return SPA_AUDIO_FORMAT_U8P;
    case AV_SAMPLE_FMT_S16P: return SPA_AUDIO_FORMAT_S16P;
    case AV_SAMPLE_FMT_S32P: return SPA_AUDIO_FORMAT_S32P;
    case AV_SAMPLE_FMT_FLTP: return SPA_AUDIO_FORMAT_F32P;
    case AV_SAMPLE_FMT_DBLP: return SPA_AUDIO_FORMAT_F64P;
    default: return 0;
  }
}

static inline int
fmt_av_from_pw(int format)
{
  switch(format) {
    case SPA_AUDIO_FORMAT_U8:     return AV_SAMPLE_FMT_U8;
    case SPA_AUDIO_FORMAT_S16_LE: return AV_SAMPLE_FMT_S16;
    case SPA_AUDIO_FORMAT_S32_LE: return AV_SAMPLE_FMT_S32;
    case SPA_AUDIO_FORMAT_F32_LE: return AV_SAMPLE_FMT_FLT;
    case SPA_AUDIO_FORMAT_F64_LE: return AV_SAMPLE_FMT_DBL;
    case SPA_AUDIO_FORMAT_U8P:    return AV_SAMPLE_FMT_U8P;
    case SPA_AUDIO_FORMAT_S16P:   return AV_SAMPLE_FMT_S16P;
    case SPA_AUDIO_FORMAT_S32P:   return AV_SAMPLE_FMT_S32P;
    case SPA_AUDIO_FORMAT_F32P:   return AV_SAMPLE_FMT_FLTP;
    case SPA_AUDIO_FORMAT_F64P:   return AV_SAMPLE_FMT_DBLP;
    default: return 0;
  }
}
